# factor_calculator.py
import os
import pandas as pd
import numpy as np
from datetime import datetime
import config
from factor_alphas_191 import *  # 导入全部因子函数
from utils import ensure_dir

def pivot_data(df, value_col):
    """将长表数据透视为宽表（日期行，股票列）"""
    return df.pivot(index='trading_day', columns='htsc_code', values=value_col)
# 生成与个股 close 同形状的 DataFrame
def align_index_data(index_series, target_df):
    # index_series: 日期索引的 Series
    # 将 index 对齐到 target_df 的日期，前向填充
    aligned = index_series.reindex(target_df.index, method='ffill')
    # 广播到所有股票列
    return pd.DataFrame(np.tile(aligned.values.reshape(-1, 1), (1, len(target_df.columns))),
                        index=target_df.index, columns=target_df.columns)

def main():
    ensure_dir(config.FACTOR_DATA_DIR)
    
    # 读取原始数据
    daily = pd.read_csv(os.path.join(config.RAW_DATA_DIR, 'daily_basic.csv'))
    daily['trading_day'] = pd.to_datetime(daily['trading_day'])
    industry = pd.read_csv(os.path.join(config.RAW_DATA_DIR, 'industry.csv'))
    benchmark= pd.read_csv(os.path.join(config.INDEX_COMPONENT_DIR , '000300.csv'))
    benchmark['date'] = pd.to_datetime(benchmark['date'])
    bench = benchmark.set_index('date')[['open', 'close']].sort_index()
    # 透视表
    close   = pivot_data(daily, 'close')
    returns = pivot_data(daily, 'pctChg')
    Open    = pivot_data(daily, 'open')
    low     = pivot_data(daily, 'low')
    high    = pivot_data(daily, 'high')
    vwap    = pivot_data(daily, 'vwap')
    cap     = pivot_data(daily, 'floating_market_val')
    volume  = pivot_data(daily, 'volume')
    ind     = industry[['htsc_code', 'l1_name']]
    index_close = align_index_data(bench['close'], close)
    index_Open  = align_index_data(bench['open'], close)


    # 计算全部因子
    start_time = datetime.now()
    
    alpha_list = []

    # alpha1 ~ alpha101 严格按顺序
    alpha_list.append(Alpha1(close, Open, volume))
    alpha_list.append(Alpha2(close, high, low))
    alpha_list.append(Alpha3(close, high, low))
    alpha_list.append(Alpha4(close, volume))
    alpha_list.append(Alpha5(high, volume))
    alpha_list.append(Alpha6(Open, high))
    alpha_list.append(Alpha7(close, volume, vwap))
    alpha_list.append(Alpha8(high, low, vwap))
    alpha_list.append(Alpha9(high, low, volume))
    alpha_list.append(Alpha10(close))
    alpha_list.append(Alpha11(close, high, low, volume))
    alpha_list.append(Alpha12(Open, close, vwap))
    alpha_list.append(Alpha13(high, low, vwap))
    alpha_list.append(Alpha14(close))
    alpha_list.append(Alpha15(Open, close))
    alpha_list.append(Alpha16(volume, vwap))
    alpha_list.append(Alpha17(close, vwap))
    alpha_list.append(Alpha18(close))
    alpha_list.append(Alpha19(close))
    alpha_list.append(Alpha20(close))
    alpha_list.append(Alpha21(close))
    alpha_list.append(Alpha22(close))
    alpha_list.append(Alpha23(close))
    alpha_list.append(Alpha24(close))
    alpha_list.append(Alpha25(close, volume))
    alpha_list.append(Alpha26(close, vwap))
    alpha_list.append(Alpha27(close))
    alpha_list.append(Alpha28(close, high, low))
    alpha_list.append(Alpha29(close, volume))
    alpha_list.append(Alpha30(close, index_close, None, None, None))  # 占位，未实现三因子回归
    alpha_list.append(Alpha31(close))
    alpha_list.append(Alpha32(high, volume))
    alpha_list.append(Alpha33(close, low, volume))
    alpha_list.append(Alpha34(close))
    alpha_list.append(Alpha35(Open, volume))
    alpha_list.append(Alpha36(volume, vwap))
    alpha_list.append(Alpha37(Open, close))
    alpha_list.append(Alpha38(high))
    alpha_list.append(Alpha39(Open, close, volume, vwap))
    alpha_list.append(Alpha40(close, volume))
    alpha_list.append(Alpha41(vwap))
    alpha_list.append(Alpha42(high, volume))
    alpha_list.append(Alpha43(close, volume))
    alpha_list.append(Alpha44(low, volume, vwap))
    alpha_list.append(Alpha45(Open, close, volume, vwap))
    alpha_list.append(Alpha46(close))
    alpha_list.append(Alpha47(close, high, low))
    alpha_list.append(Alpha48(close, volume))
    alpha_list.append(Alpha49(high, low))
    alpha_list.append(Alpha50(high, low))
    alpha_list.append(Alpha51(high, low))
    alpha_list.append(Alpha52(close, high, low))
    alpha_list.append(Alpha53(close))
    alpha_list.append(Alpha54(Open, close))
    alpha_list.append(Alpha55(Open, close, high, low))          # 占位，返回全0
    alpha_list.append(Alpha56(Open, high, low, volume))
    alpha_list.append(Alpha57(close, high, low))
    alpha_list.append(Alpha58(close))
    alpha_list.append(Alpha59(close, high, low))
    alpha_list.append(Alpha60(close, high, low, volume))
    alpha_list.append(Alpha61(low, volume, vwap))
    alpha_list.append(Alpha62(high, volume))
    alpha_list.append(Alpha63(close))
    alpha_list.append(Alpha64(close, volume, vwap))
    alpha_list.append(Alpha65(close))
    alpha_list.append(Alpha66(close))
    alpha_list.append(Alpha67(close))
    alpha_list.append(Alpha68(high, low, volume))
    alpha_list.append(Alpha69(Open, high, low))
    alpha_list.append(Alpha70(volume, vwap))
    alpha_list.append(Alpha71(close))
    alpha_list.append(Alpha72(close, high, low))
    alpha_list.append(Alpha73(close, volume, vwap))
    alpha_list.append(Alpha74(low, volume, vwap))
    alpha_list.append(Alpha75(Open, close, index_Open, index_close))
    alpha_list.append(Alpha76(close, volume))
    alpha_list.append(Alpha77(high, low, volume, vwap))
    alpha_list.append(Alpha78(close, high, low))
    alpha_list.append(Alpha79(close))
    alpha_list.append(Alpha80(volume))
    alpha_list.append(Alpha81(volume))
    alpha_list.append(Alpha82(close, high, low))
    alpha_list.append(Alpha83(high, volume))
    alpha_list.append(Alpha84(close, volume))
    alpha_list.append(Alpha85(close, volume))
    alpha_list.append(Alpha86(close))
    alpha_list.append(Alpha87(Open, high, low, vwap))
    alpha_list.append(Alpha88(close))
    alpha_list.append(Alpha89(close))
    alpha_list.append(Alpha90(volume, vwap))
    alpha_list.append(Alpha91(close, low, volume))
    alpha_list.append(Alpha92(close, volume, vwap))
    alpha_list.append(Alpha93(Open, low))
    alpha_list.append(Alpha94(close, volume))
    alpha_list.append(Alpha95(volume, vwap))
    alpha_list.append(Alpha96(close, high, low))
    alpha_list.append(Alpha97(volume))
    alpha_list.append(Alpha98(close))
    alpha_list.append(Alpha99(close, volume))
    alpha_list.append(Alpha100(volume))
    alpha_list.append(Alpha101(close, high, volume, vwap))
    alpha_list.append(Alpha102(volume))
    alpha_list.append(Alpha103(low))
    alpha_list.append(Alpha104(close, high, volume))
    alpha_list.append(Alpha105(Open, volume))
    alpha_list.append(Alpha106(close))
    alpha_list.append(Alpha107(Open, close, high, low))
    alpha_list.append(Alpha108(high, volume, vwap))
    alpha_list.append(Alpha109(high, low))
    alpha_list.append(Alpha110(close, high, low))
    alpha_list.append(Alpha111(close, high, low, volume))
    alpha_list.append(Alpha112(close))
    alpha_list.append(Alpha113(close, volume))
    alpha_list.append(Alpha114(close, high, low, volume, vwap))
    alpha_list.append(Alpha115(close, high, low, volume))
    alpha_list.append(Alpha116(close))
    alpha_list.append(Alpha117(close, high, low, volume))
    alpha_list.append(Alpha118(Open, high, low))
    alpha_list.append(Alpha119(Open, volume, vwap))
    alpha_list.append(Alpha120(close, vwap))
    alpha_list.append(Alpha121(volume, vwap))
    alpha_list.append(Alpha122(close))
    alpha_list.append(Alpha123(high, low, volume))
    alpha_list.append(Alpha124(close, vwap))
    alpha_list.append(Alpha125(close, volume, vwap))
    alpha_list.append(Alpha126(close, high, low))
    alpha_list.append(Alpha127(close))
    alpha_list.append(Alpha128(close, high, low, volume))
    alpha_list.append(Alpha129(close))
    alpha_list.append(Alpha130(high, low, volume, vwap))
    alpha_list.append(Alpha131(close, volume, vwap))
    alpha_list.append(Alpha132(volume, vwap))
    alpha_list.append(Alpha133(high, low))
    alpha_list.append(Alpha134(close, volume))
    alpha_list.append(Alpha135(close))
    alpha_list.append(Alpha136(Open, close, volume))
    alpha_list.append(Alpha137(Open, close, high, low))   # 占位，返回全0
    alpha_list.append(Alpha138(low, volume, vwap))
    alpha_list.append(Alpha139(Open, volume))
    alpha_list.append(Alpha140(Open, close, high, low, volume))
    alpha_list.append(Alpha141(high, volume))
    alpha_list.append(Alpha142(close, volume))
    alpha_list.append(Alpha143(close))
    alpha_list.append(Alpha144(close, volume, vwap))
    alpha_list.append(Alpha145(volume))
    alpha_list.append(Alpha146(close))
    alpha_list.append(Alpha147(close))
    alpha_list.append(Alpha148(Open, volume))
    alpha_list.append(Alpha149(close, index_close))
    alpha_list.append(Alpha150(close, high, low, volume))
    alpha_list.append(Alpha151(close))
    alpha_list.append(Alpha152(close))
    alpha_list.append(Alpha153(close))
    alpha_list.append(Alpha154(volume, vwap))
    alpha_list.append(Alpha155(volume))
    alpha_list.append(Alpha156(Open, low, vwap))
    alpha_list.append(Alpha157(close, returns))
    alpha_list.append(Alpha158(close, high, low))
    alpha_list.append(Alpha159(close, high, low))
    alpha_list.append(Alpha160(close))
    alpha_list.append(Alpha161(close, high, low))
    alpha_list.append(Alpha162(close))
    alpha_list.append(Alpha163(close, high, volume, vwap))
    alpha_list.append(Alpha164(close, high, low))
    alpha_list.append(Alpha165(close))
    alpha_list.append(Alpha166(close))
    alpha_list.append(Alpha167(close))
    alpha_list.append(Alpha168(volume))
    alpha_list.append(Alpha169(close))
    alpha_list.append(Alpha170(close, high, volume, vwap))
    alpha_list.append(Alpha171(Open, close, high, low))
    alpha_list.append(Alpha172(close, high, low))
    alpha_list.append(Alpha173(close))
    alpha_list.append(Alpha174(close))
    alpha_list.append(Alpha175(close, high, low))
    alpha_list.append(Alpha176(close, high, low, volume))
    alpha_list.append(Alpha177(high))
    alpha_list.append(Alpha178(close, volume))
    alpha_list.append(Alpha179(low, volume, vwap))
    alpha_list.append(Alpha180(close, volume))
    alpha_list.append(Alpha181(close, index_close))
    alpha_list.append(Alpha182(Open, close, index_Open, index_close))
    alpha_list.append(Alpha183(close))
    alpha_list.append(Alpha184(Open, close))
    alpha_list.append(Alpha185(Open, close))
    alpha_list.append(Alpha186(close, high, low))
    alpha_list.append(Alpha187(Open, high))
    alpha_list.append(Alpha188(high, low))
    alpha_list.append(Alpha189(close))
    alpha_list.append(Alpha190(close))                        # 占位，返回全0
    alpha_list.append(Alpha191(close, high, low, volume))
        
    # 截断前 245 行（约一年数据）以消除计算窗口影响
    for i in range(len(alpha_list)):
        alpha_list[i] = alpha_list[i].iloc[245:]
    
    # 合并并保存
    # 合并并保存
    df_all = pd.concat(alpha_list, axis=1)   # 明确 axis=1 按列合并因子
    # 设置索引名称为 trading_day
    df_all.index.name = 'trading_day'
    # 将索引日期格式化为 YYYY-MM-DD
    df_all.index = df_all.index.strftime('%Y-%m-%d')
    # 保存 CSV，默认包含索引作为第一列
    df_all.to_csv(os.path.join(config.FACTOR_DATA_DIR, 'alpha191.csv'))
    print(f"因子计算完成，耗时 {datetime.now() - start_time}")

if __name__ == '__main__':
    main()